# Generated by Django 6.1 on 2026-08-15 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=20)),
                ('options', models.JSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('cards', models.JSONField(default=list)),
                ('unresolved', models.JSONField(default=list)),
                ('unsupported', models.JSONField(default=list)),
                ('results', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
