# Generated by Django 6.1 on 2026-08-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='worker_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
