#!/usr/bin/env python3
"""DFC spike — does a double-faced card render, and do the two faces read as a PAIR?

Face-pair coherence is the failure mode ordinary cards cannot have: two faces of one card,
generated by two independent API calls, can come back as two unrelated pictures. Nothing in
the 19-card spike tested this, and DFC is the client's priority-1 layout.

The experiment, two conditions per card:

  independent  face A and face B generated from their own prompts, no link between them
  linked       face B's request carries face A's IMAGE as a reference, told to match it

Coherence is then MEASURED, not eyeballed: hue/saturation/value histogram distance between
the two faces, plus mean-colour delta. A number, so "coherent" is falsifiable.

Per the build spec the AI paints ART + NAME only; type line, rules text, pips and P/T are
composited by us, so this spike prompts for the name and deliberately NOT for the body text.
No bottom hint bar — decided omitted (BUILD-SPEC 9.1).

Run:  python3 spike_dfc.py
Out:  evidence-dfc/*.png + evidence-dfc/coherence.json
Cost: 2 cards x 2 faces x 2 conditions = 8 generations, ~$1.05 on the client's key.
"""
import base64, io, json, pathlib, re, sys, time
import numpy as np
import requests
from PIL import Image

API = "https://generativelanguage.googleapis.com/v1beta/models"
KEY = next(l.split("=", 1)[1].strip() for l in open(".env") if l.startswith("GEMINI_API_KEY"))
OUT = pathlib.Path("evidence-dfc"); OUT.mkdir(exist_ok=True)
PRO, READER = "gemini-3-pro-image", "gemini-3.6-flash"
HDR = {"User-Agent": "mtg-proxy-evidence/0.4"}

STYLE = ("toxic neon adult-cartoon illustration, bold heavy black ink outlines on every shape, "
         "acid green and violet neon glow, psychedelic slime and vapour, flat cel shading with "
         "airbrushed neon rim light, dense detail edge to edge, high contrast")

CARDS = ["Turntimber Symbiosis", "Huntmaster of the Fells"]
COLOUR = {"W": "white", "U": "blue", "B": "black", "R": "red", "G": "green"}
PALETTE = {"white": "ivory and gold", "blue": "deep blues and cyans",
           "black": "deep violet, magenta and bruised purple",
           "red": "molten orange and crimson", "green": "verdant greens and moss",
           "colourless": "cold grey stone and steel"}


def scryfall(name):
    r = requests.get("https://api.scryfall.com/cards/named",
                     params={"fuzzy": name}, headers=HDR, timeout=30)
    r.raise_for_status()
    return r.json()


def split_faces(c):
    """A DFC's real data lives per-face in card_faces[]; the top level is useless for rendering.

    Top-level `oracle_text` is absent entirely and top-level `type_line` is the two faces joined
    with '//'. So each face becomes its own card-shaped dict.

    The trap: a back face often has colors == [] (a transforming land, for instance) while the
    CARD is coloured. Rendering that face colourless would break pair coherence on its own, so
    fall back to the card-level color_identity.
    """
    if "card_faces" not in c:
        return [dict(c, _face=0, _of=1)]
    out = []
    for i, f in enumerate(c["card_faces"]):
        colours = f.get("colors") or c.get("color_identity") or []
        out.append({"name": f["name"], "type_line": f.get("type_line", ""),
                    "oracle_text": f.get("oracle_text", ""),
                    "mana_cost": f.get("mana_cost", ""),
                    "colors": colours,
                    "power": f.get("power"), "toughness": f.get("toughness"),
                    "_face": i, "_of": len(c["card_faces"]), "_card": c["name"]})
    return out


def prompt_face(f, pair_note=""):
    colours = [COLOUR[x] for x in f["colors"]] or ["colourless"]
    pal = ", ".join(PALETTE[x] for x in colours)
    subject = (f.get("oracle_text") or "").replace("\n", " / ")[:200]
    return f"""A complete fantasy trading card, portrait, full bleed, art to every edge.

Scene: {f['name']} — a dense, dramatic illustration with one clear central subject filling the
upper two thirds. What is happening: {subject}

COLOUR: the palette is {pal}. This is a {'/'.join(colours)} card and must read as one at a glance.

STYLE: {STYLE}
{pair_note}
PAINT THE CARD NAME, hand-lettered across the top as part of the artwork, on a decorative
surface that belongs to the scene. It must read exactly, letter for letter:
    {f['name']}

Leave the lower third of the card visually calm and uncluttered — no important detail there,
no lettering, no ornament crossing it. Text will be placed into that area afterwards.

Write NO other words anywhere — no type line, no rules text, no numbers, no flavour text,
no runes, no invented glyphs, no artist signature, no watermark, no logo."""


PAIR_NOTE = """
PAIR MATCHING — CRITICAL: the reference image provided is the OTHER FACE of this same physical
card. This face must look like it was painted by the same artist in the same sitting: identical
palette, identical outline weight, identical rendering technique, same world and lighting. It is
a transformation of the same subject, not a different card."""


def generate(prompt, label, ref_image: pathlib.Path | None = None):
    parts = [{"text": prompt}]
    if ref_image:
        parts.insert(0, {"inline_data": {
            "mime_type": "image/png",
            "data": base64.b64encode(ref_image.read_bytes()).decode()}})
    body = {"contents": [{"parts": parts}],
            "generationConfig": {"responseModalities": ["TEXT", "IMAGE"],
                                 "imageConfig": {"aspectRatio": "3:4", "imageSize": "2K"}}}
    t0 = time.time()
    r = requests.post(f"{API}/{PRO}:generateContent", params={"key": KEY}, json=body, timeout=420)
    if r.status_code != 200:
        print(f"  FAIL {label}: {r.status_code} {r.text[:300]}")
        return None, 0
    for p in r.json()["candidates"][0]["content"]["parts"]:
        if "inlineData" in p:
            path = OUT / f"{label}.png"
            path.write_bytes(base64.b64decode(p["inlineData"]["data"]))
            dt = round(time.time() - t0, 1)
            print(f"  ok   {label}  {dt}s  {path.stat().st_size // 1024}KB")
            return path, dt
    print(f"  FAIL {label}: no image in response")
    return None, 0


def read_name(path):
    """Only the name matters now — everything else is composited by us."""
    raw = base64.b64encode(path.read_bytes()).decode()
    body = {"contents": [{"parts": [
        {"inline_data": {"mime_type": "image/png", "data": raw}},
        {"text": 'Transcribe ONLY the large card name painted at the top of this card, exactly as '
                 'it appears, no correction. Reply as JSON: {"name": "..."} — empty string if none.'}]}],
        "generationConfig": {"responseMimeType": "application/json"}}
    r = requests.post(f"{API}/{READER}:generateContent", params={"key": KEY}, json=body, timeout=180)
    if r.status_code != 200:
        return ""
    try:
        return json.loads(r.json()["candidates"][0]["content"]["parts"][0]["text"]).get("name", "")
    except Exception:
        return ""


def coherence(a: pathlib.Path, b: pathlib.Path):
    """How alike are two faces? Lower distance = more coherent. Measured, not judged."""
    def feats(p):
        im = Image.open(p).convert("RGB").resize((256, 341))
        hsv = np.asarray(im.convert("HSV"), dtype=np.float32)
        rgb = np.asarray(im, dtype=np.float32)
        hists = []
        for ch in range(3):
            h, _ = np.histogram(hsv[:, :, ch], bins=32, range=(0, 256), density=True)
            hists.append(h)
        return np.concatenate(hists), rgb.reshape(-1, 3).mean(0)

    ha, ma = feats(a)
    hb, mb = feats(b)
    # Bhattacharyya-style overlap on the HSV histogram: 1.0 = identical distribution
    overlap = float(np.sum(np.sqrt(np.clip(ha, 0, None) * np.clip(hb, 0, None))) /
                    max(np.sum(np.sqrt(np.clip(ha, 0, None) * np.clip(ha, 0, None))), 1e-9))
    return {"hsv_overlap": round(min(overlap, 1.0), 3),
            "mean_rgb_delta": round(float(np.linalg.norm(ma - mb)), 1),
            "mean_a": [round(x) for x in ma], "mean_b": [round(x) for x in mb]}


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


if __name__ == "__main__":
    results, gens, total_time = [], 0, 0.0
    for card_name in CARDS:
        c = scryfall(card_name)
        faces = split_faces(c)
        print(f"\n=== {c['name']}  layout={c['layout']}  faces={len(faces)}")
        if len(faces) < 2:
            print("  not a DFC, skipping"); continue

        row = {"card": c["name"], "layout": c["layout"],
               "color_identity": c.get("color_identity"),
               "faces": [f["name"] for f in faces], "conditions": {}}

        for cond in ("independent", "linked"):
            paths = []
            for i, f in enumerate(faces[:2]):
                label = f"{slug(c['name'])[:28]}-{cond}-{i}-{slug(f['name'])[:20]}"
                ref = paths[0] if (cond == "linked" and i == 1 and paths) else None
                note = PAIR_NOTE if ref else ""
                p, dt = generate(prompt_face(f, note), label, ref_image=ref)
                gens += 1; total_time += dt
                if not p:
                    break
                paths.append(p)
            if len(paths) == 2:
                coh = coherence(paths[0], paths[1])
                names = [read_name(p) for p in paths]
                name_ok = [n.strip().lower() == f["name"].strip().lower()
                           for n, f in zip(names, faces[:2])]
                row["conditions"][cond] = {**coh, "files": [p.name for p in paths],
                                           "names_read": names, "name_exact": name_ok}
                print(f"  -> {cond}: hsv_overlap={coh['hsv_overlap']} "
                      f"rgb_delta={coh['mean_rgb_delta']} names_exact={name_ok}")
            else:
                row["conditions"][cond] = {"error": "a face failed to generate"}
        results.append(row)

    summary = {"generations": gens, "est_cost_usd": round(gens * 0.13, 2),
               "total_generate_seconds": round(total_time, 1), "cards": results}
    json.dump(summary, open(OUT / "coherence.json", "w"), indent=2)
    print(f"\n{gens} generations, ~${summary['est_cost_usd']}, {total_time:.0f}s total")
    for r in results:
        ind = r["conditions"].get("independent", {}).get("hsv_overlap")
        lin = r["conditions"].get("linked", {}).get("hsv_overlap")
        print(f"  {r['card'][:40]:42s} independent={ind}  linked={lin}")
